Feature: OpenTofu Support
  As a platform engineer using OpenTofu
  I want terrapyne to auto-detect and use the correct IaC runner
  So that I can safely manage infrastructure without state corruption

  Background:
    Given a workspace directory exists

  # --- Heuristic Auto-Detection ---

  Scenario: Lockfile generated by terraform selects terraform runner
    Given the lockfile was generated by "terraform init"
    When the runner is detected
    Then the detected runner is "terraform"

  Scenario: Lockfile generated by tofu selects opentofu runner
    Given the lockfile was generated by "tofu init"
    When the runner is detected
    Then the detected runner is "opentofu"

  Scenario: Version file .opentofu-version selects opentofu runner
    Given the file ".opentofu-version" exists with content "1.8.0"
    When the runner is detected
    Then the detected runner is "opentofu"

  Scenario: Version file .terraform-version selects terraform runner
    Given the file ".terraform-version" exists with content "1.9.0"
    When the runner is detected
    Then the detected runner is "terraform"

  # --- Safety Rules ---

  Scenario: Detection fails when the required binary is not installed
    Given the lockfile was generated by "tofu init"
    And the "tofu" binary is not in PATH
    When the runner is detected without the binary available
    Then detection fails because the binary is missing

  Scenario: Detection fails for a brand-new project with no signals
    Given the workspace directory is empty
    When the runner is detected
    Then detection fails because the runner is ambiguous

  # --- Explicit Override ---

  Scenario: Explicit override bypasses heuristic detection
    Given the lockfile was generated by "terraform init"
    When the runner is detected with force override "tofu"
    Then the detected runner is "opentofu"

  # --- Factory ---

  Scenario: Factory returns a Terraform instance for terraform projects
    Given the lockfile was generated by "terraform init"
    When a runner instance is created from the workspace
    Then the instance is a Terraform runner

  Scenario: Factory returns an OpenTofu instance for opentofu projects
    Given the lockfile was generated by "tofu init"
    When a runner instance is created from the workspace
    Then the instance is an OpenTofu runner
