[tool.poetry]
name = "terrapyne"
version = "0.0.1"
description = "Wrapper around terraform"
authors = []
license = "Apache License Version 2.0"
readme = "README.md"
homepage = "https://github.com/shalomb/terrapyne"
keywords = ["terraform", "wrapper"]

# For reference, see https://pypi.org/pypi?%3Aaction=list_classifiers
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Intended Audience :: System Administrators",
  "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: System :: Systems Administration",
  "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = ">=3.11.1,<4.0"
colorlog = ">=5.0.1,<7.0.0"
jinja2 = "^3.0.1"
pretty_traceback = "*"

[tool.poetry.group.test.dependencies]
black = "*"
coverage = "*"
flake8 = ">=6.0.0"
flake8-docstrings = "*"
flake8-pyproject = "*"
md-toc = "*"
mock = "*"
pook = ">=1.0.2"
pre-commit = "*"
pytest = "*"
pytest-mock = "*"
requests-mock = "*"
toml = "*"
tox = ">=4"

[tool.poetry.scripts]
tfwrapper = 'terrapyne:main'

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
# Make sure to match flake8's max-line-length.
line-length = 130 # black's default
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
exclude = '''
/(
  \.git
  | \.pytest_cache
  | \.tox
  | \.venv
)/
'''

[tool.flake8]
verbose = 3
max-line-length = 130
per-file-ignores = ['tests/*.py:D103']
exclude = ['.git', '.tox', '.venv', '.virtualenv', '__pycache__']
# See https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated
ignore = ['E203', 'W503']
enable-extensions = ['W504']
