"""BDD steps for tfc local CLI commands."""

from unittest.mock import patch

from pytest_bdd import given, parsers, scenario, then, when
from typer.testing import CliRunner

from terrapyne.cli.main import app

runner = CliRunner()


@scenario(
    "../features/opentofu_support.feature",
    "CLI local info shows detected runner",
)
def test_cli_local_info():
    pass


@scenario(
    "../features/opentofu_support.feature",
    "CLI local info with --force-runner overrides detection",
)
def test_cli_local_info_force_runner():
    pass


# --- Given ---


@given("a workspace directory exists", target_fixture="workspace_dir")
def workspace_dir(tmp_path):
    return tmp_path


@given(
    parsers.parse('the lockfile was generated by "{tool}"'),
    target_fixture="workspace_dir",
)
def lockfile_generated_by(workspace_dir, tool: str):
    (workspace_dir / ".terraform.lock.hcl").write_text(
        f'# This file is maintained automatically by "{tool}".\n'
    )
    return workspace_dir


# --- When ---


@when(parsers.parse('I run "{command}"'), target_fixture="cli_result")
def run_cli_command(workspace_dir, command: str):
    args = command.replace("tfc ", "").split()
    # Inject --directory if not already present
    if "--directory" not in args and "-d" not in args:
        args.extend(["--directory", str(workspace_dir)])
    with patch("terrapyne.core.runner_detection.which", return_value="/usr/bin/fake"):
        result = runner.invoke(app, args)
    return result


# --- Then ---


@then(parsers.parse('the output contains "{text}"'))
def output_contains(cli_result, text: str):
    assert text in cli_result.output, f"Expected '{text}' in: {cli_result.output}"
