name: Bug Report
description: Create a report to help us improve Terrapyne
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Terrapyne Version
      description: What version of Terrapyne are you using? (Run `tfc --version`)
      placeholder: "0.1.0"
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.12"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running on? (e.g., macOS Sonoma, Ubuntu 22.04, Windows 11)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this behavior?
      value: |
        1. Run `tfc ...`
        2. See error ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. Run your command with the `--debug` flag if possible. Remember to sanitize any sensitive data!
      render: shell
