"""BDD steps for OpenTofu support — runner auto-detection.

Each scenario follows a clean Given/When/Then with no branching logic
in step implementations. Mocks are applied at the scenario level via
dedicated When steps.
"""

from pathlib import Path
from unittest.mock import patch

from pytest_bdd import given, parsers, scenario, then, when

from terrapyne.core.local_binary import OpenTofu, Terraform
from terrapyne.core.runner_detection import (
    AmbiguousRunnerError,
    RunnerNotFoundError,
    create_runner,
    detect_runner,
)

# --- Scenario declarations ---


@scenario(
    "../features/opentofu_support.feature",
    "Lockfile generated by terraform selects terraform runner",
)
def test_lockfile_terraform():
    pass


@scenario(
    "../features/opentofu_support.feature",
    "Lockfile generated by tofu selects opentofu runner",
)
def test_lockfile_opentofu():
    pass


@scenario(
    "../features/opentofu_support.feature",
    "Version file .opentofu-version selects opentofu runner",
)
def test_version_file_opentofu():
    pass


@scenario(
    "../features/opentofu_support.feature",
    "Version file .terraform-version selects terraform runner",
)
def test_version_file_terraform():
    pass


@scenario(
    "../features/opentofu_support.feature",
    "Detection fails when the required binary is not installed",
)
def test_binary_not_installed():
    pass


@scenario(
    "../features/opentofu_support.feature",
    "Detection fails for a brand-new project with no signals",
)
def test_ambiguous_project():
    pass


@scenario(
    "../features/opentofu_support.feature",
    "Explicit override bypasses heuristic detection",
)
def test_explicit_override():
    pass


@scenario(
    "../features/opentofu_support.feature",
    "Factory returns a Terraform instance for terraform projects",
)
def test_factory_terraform():
    pass


@scenario(
    "../features/opentofu_support.feature",
    "Factory returns an OpenTofu instance for opentofu projects",
)
def test_factory_opentofu():
    pass


@scenario(
    "../features/opentofu_support.feature",
    "TERRAPYNE_RUNNER env var selects runner for new projects",
)
def test_env_var_selects_runner():
    pass


@scenario(
    "../features/opentofu_support.feature",
    "Heuristic takes precedence over TERRAPYNE_RUNNER",
)
def test_heuristic_over_env_var():
    pass


# --- Given steps ---


@given("a workspace directory exists", target_fixture="workspace_dir")
def workspace_dir(tmp_path: Path) -> Path:
    return tmp_path


@given(
    parsers.parse('the lockfile was generated by "{tool}"'),
    target_fixture="workspace_dir",
)
def lockfile_generated_by(workspace_dir: Path, tool: str) -> Path:
    (workspace_dir / ".terraform.lock.hcl").write_text(
        f'# This file is maintained automatically by "{tool}".\n'
    )
    return workspace_dir


@given(
    parsers.parse('the file "{filename}" exists with content "{content}"'),
    target_fixture="workspace_dir",
)
def file_with_content(workspace_dir: Path, filename: str, content: str) -> Path:
    (workspace_dir / filename).write_text(content)
    return workspace_dir


@given(parsers.parse('the "{binary}" binary is not in PATH'))
def binary_not_in_path():
    # Marker step — the When step for this scenario patches which() to None
    pass


@given("the workspace directory is empty")
def workspace_is_empty():
    pass


@given(
    parsers.parse('the environment variable "{var}" is set to "{value}"'),
    target_fixture="env_override",
)
def env_var_set(var: str, value: str, monkeypatch) -> tuple[str, str]:
    monkeypatch.setenv(var, value)
    return (var, value)


# --- When steps ---


@when("the runner is detected", target_fixture="detection_result")
def detect_runner_normally(workspace_dir: Path):
    """Detect with binary check mocked to always succeed."""
    with patch("terrapyne.core.runner_detection.which", return_value="/usr/bin/fake"):
        try:
            return detect_runner(workspace_dir)
        except (RunnerNotFoundError, AmbiguousRunnerError) as e:
            return e


@when("the runner is detected without the binary available", target_fixture="detection_result")
def detect_runner_missing_binary(workspace_dir: Path):
    """Detect with which() returning None — binary not installed."""
    with patch("terrapyne.core.runner_detection.which", return_value=None):
        try:
            return detect_runner(workspace_dir)
        except (RunnerNotFoundError, AmbiguousRunnerError) as e:
            return e


@when(
    parsers.parse('the runner is detected with force override "{runner}"'),
    target_fixture="detection_result",
)
def detect_runner_with_override(workspace_dir: Path, runner: str):
    return detect_runner(workspace_dir, force_runner=runner)


# --- Then steps ---


@then(parsers.parse('the detected runner is "{expected}"'))
def assert_runner_is(detection_result: str, expected: str):
    assert detection_result == expected


@then("detection fails because the binary is missing")
def assert_binary_missing(detection_result):
    assert isinstance(detection_result, RunnerNotFoundError)


@then("detection fails because the runner is ambiguous")
def assert_ambiguous(detection_result):
    assert isinstance(detection_result, AmbiguousRunnerError)


@when("a runner instance is created from the workspace", target_fixture="runner_instance")
def create_runner_instance(workspace_dir: Path):
    with (
        patch("terrapyne.core.runner_detection.which", return_value="/usr/bin/fake"),
        patch("terrapyne.core.local_binary.which", return_value="/usr/bin/fake"),
        patch.object(Terraform, "version", new_callable=lambda: property(lambda self: "1.9.0")),
        patch.object(OpenTofu, "version", new_callable=lambda: property(lambda self: "1.8.0")),
    ):
        return create_runner(workspace_dir)


@then("the instance is a Terraform runner")
def assert_terraform_instance(runner_instance):
    assert isinstance(runner_instance, Terraform)


@then("the instance is an OpenTofu runner")
def assert_opentofu_instance(runner_instance):
    assert isinstance(runner_instance, OpenTofu)
